name: sticky_session_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.1
  shared_preferences: ^2.0.12
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3

flutter_native_splash:
  color: "#42023e"
  image: assets/splash.png
  android: true
  ios: true
  #web: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/profile.png
    - assets/sad_face.png
  
